export const TOGGLE_SIDEBAR_DOCKED = 'TOGGLE_SIDEBAR_DOCKED';

export const CHANGE_UPDATING_NEW_VERSION = 'CHANGE_UPDATING_NEW_VERSION';
export const TOGGLE_UPDATING_DIALOG_VISIBLE = 'TOGGLE_UPDATING_DIALOG_VISIBLE';

export const CHANGE_SECTION_TITLE = 'CHANGE_SECTION_TITLE';
export const CHANGE_SECTION_LINK = 'CHANGE_SECTION_LINK';
