export const GET_APARTMENT_STATUSES_REQUEST = 'GET_APARTMENT_STATUSES_REQUEST';
export const GET_APARTMENT_STATUSES_SUCCESS = 'GET_APARTMENT_STATUSES_SUCCESS';
export const GET_APARTMENT_STATUSES_FAILURE = 'GET_APARTMENT_STATUSES_FAILURE';
