export const GET_OBJECTS_REQUEST = 'GET_OBJECTS_REQUEST';
export const GET_OBJECTS_SUCCESS = 'GET_OBJECTS_SUCCESS';
export const GET_OBJECTS_FAILURE = 'GET_OBJECTS_FAILURE';

export const GET_OBJECT_REQUEST = 'GET_OBJECT_REQUEST';
export const GET_OBJECT_SUCCESS = 'GET_OBJECT_SUCCESS';
export const GET_OBJECT_FAILURE = 'GET_OBJECT_FAILURE';

export const ADD_OBJECT_REQUEST = 'ADD_OBJECT_REQUEST';
export const ADD_OBJECT_SUCCESS = 'ADD_OBJECT_SUCCESS';
export const ADD_OBJECT_FAILURE = 'ADD_OBJECT_FAILURE';

export const EDIT_OBJECT_REQUEST = 'EDIT_OBJECT_REQUEST';
export const EDIT_OBJECT_SUCCESS = 'EDIT_OBJECT_SUCCESS';
export const EDIT_OBJECT_FAILURE = 'EDIT_OBJECT_FAILURE';

export const DELETE_OBJECT_REQUEST = 'DELETE_OBJECT_REQUEST';
export const DELETE_OBJECT_SUCCESS = 'DELETE_OBJECT_SUCCESS';
export const DELETE_OBJECT_FAILURE = 'DELETE_OBJECT_FAILURE';
