export const GET_PLANS_REQUEST = 'GET_PLANS_REQUEST';
export const GET_PLANS_SUCCESS = 'GET_PLANS_SUCCESS';
export const GET_PLANS_FAILURE = 'GET_PLANS_FAILURE';

export const ADD_PLAN_REQUEST = 'ADD_PLAN_REQUEST';
export const ADD_PLAN_SUCCESS = 'ADD_PLAN_SUCCESS';
export const ADD_PLAN_FAILURE = 'ADD_PLAN_FAILURE';

export const EDIT_PLAN_REQUEST = 'EDIT_PLAN_REQUEST';
export const EDIT_PLAN_SUCCESS = 'EDIT_PLAN_SUCCESS';
export const EDIT_PLAN_FAILURE = 'EDIT_PLAN_FAILURE';

export const EDIT_PLANS_ORDER_REQUEST = 'EDIT_PLANS_ORDER_REQUEST';
export const EDIT_PLANS_ORDER_SUCCESS = 'EDIT_PLANS_ORDER_SUCCESS';
export const EDIT_PLANS_ORDER_FAILURE = 'EDIT_PLANS_ORDER_FAILURE';

export const DELETE_PLAN_REQUEST = 'DELETE_PLAN_REQUEST';
export const DELETE_PLAN_SUCCESS = 'DELETE_PLAN_SUCCESS';
export const DELETE_PLAN_FAILURE = 'DELETE_PLAN_FAILURE';
