export const ADD_PROBLEM_REPLY_REQUEST = 'ADD_PROBLEM_REPLY_REQUEST';
export const ADD_PROBLEM_REPLY_SUCCESS = 'ADD_PROBLEM_REPLY_SUCCESS';
export const ADD_PROBLEM_REPLY_FAILURE = 'ADD_PROBLEM_REPLY_FAILURE';

export const EDIT_PROBLEM_REPLY_REQUEST = 'EDIT_PROBLEM_REPLY_REQUEST';
export const EDIT_PROBLEM_REPLY_SUCCESS = 'EDIT_PROBLEM_REPLY_SUCCESS';
export const EDIT_PROBLEM_REPLY_FAILURE = 'EDIT_PROBLEM_REPLY_FAILURE';

export const DELETE_PROBLEM_REPLY_REQUEST = 'DELETE_PROBLEM_REPLY_REQUEST';
export const DELETE_PROBLEM_REPLY_SUCCESS = 'DELETE_PROBLEM_REPLY_SUCCESS';
export const DELETE_PROBLEM_REPLY_FAILURE = 'DELETE_PROBLEM_REPLY_FAILURE';

export const EXPORT_PROBLEM_REPLY_REQUEST = 'EXPORT_PROBLEM_REPLY_REQUEST';
export const EXPORT_PROBLEM_REPLY_SUCCESS = 'EXPORT_PROBLEM_REPLY_SUCCESS';
export const EXPORT_PROBLEM_REPLY_FAILURE = 'EXPORT_PROBLEM_REPLY_FAILURE';

export const SEND_PROBLEM_REPLY_REQUEST = 'SEND_PROBLEM_REPLY_REQUEST';
export const SEND_PROBLEM_REPLY_SUCCESS = 'SEND_PROBLEM_REPLY_SUCCESS';
export const SEND_PROBLEM_REPLY_FAILURE = 'SEND_PROBLEM_REPLY_FAILURE';
