export const GET_REGULATORY_STANDARDS_REQUEST = 'GET_REGULATORY_STANDARDS_REQUEST';
export const GET_REGULATORY_STANDARDS_SUCCESS = 'GET_REGULATORY_STANDARDS_SUCCESS';
export const GET_REGULATORY_STANDARDS_FAILURE = 'GET_REGULATORY_STANDARDS_FAILURE';
