export const GET_REPORTS_USERS_REQUEST = 'GET_REPORTS_USERS_REQUEST';
export const GET_REPORTS_USERS_SUCCESS = 'GET_REPORTS_USERS_SUCCESS';
export const GET_REPORTS_USERS_FAILURE = 'GET_REPORTS_USERS_FAILURE';
