export const EXPORT_COMPANIES_SUMMARY_REQUEST = 'EXPORT_COMPANIES_SUMMARY_REQUEST';
export const EXPORT_COMPANIES_SUMMARY_SUCCESS = 'EXPORT_COMPANIES_SUMMARY_SUCCESS';
export const EXPORT_COMPANIES_SUMMARY_FAILURE = 'EXPORT_COMPANIES_SUMMARY_FAILURE';

export const GET_COMPANIES_SUMMARY_REQUEST = 'GET_COMPANIES_SUMMARY_REQUEST';
export const GET_COMPANIES_SUMMARY_SUCCESS = 'GET_COMPANIES_SUMMARY_SUCCESS';
export const GET_COMPANIES_SUMMARY_FAILURE = 'GET_COMPANIES_SUMMARY_FAILURE';

