export const GET_TEMP_FILES_REQUEST = 'GET_TEMP_FILES_REQUEST';
export const GET_TEMP_FILES_SUCCESS = 'GET_TEMP_FILES_SUCCESS';
export const GET_TEMP_FILES_FAILURE = 'GET_TEMP_FILES_FAILURE';

export const ADD_TEMP_FILE_REQUEST = 'ADD_TEMP_FILE_REQUEST';
export const ADD_TEMP_FILE_SUCCESS = 'ADD_TEMP_FILE_SUCCESS';
export const ADD_TEMP_FILE_FAILURE = 'ADD_TEMP_FILE_FAILURE';

export const DELETE_TEMP_FILE_REQUEST = 'DELETE_TEMP_FILE_REQUEST';
export const DELETE_TEMP_FILE_SUCCESS = 'DELETE_TEMP_FILE_SUCCESS';
export const DELETE_TEMP_FILE_FAILURE = 'DELETE_TEMP_FILE_FAILURE';
