export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const CLEAR_STORE = 'CLEAR_STORE';

export const UPDATE_TOKENS_REQUEST = 'UPDATE_TOKENS_REQUEST';
export const UPDATE_TOKENS_SUCCESS = 'UPDATE_TOKENS_SUCCESS';
export const UPDATE_TOKENS_FAILURE = 'UPDATE_TOKENS_FAILURE';

export const CHECK_AUTH_REQUEST = 'CHECK_AUTH_REQUEST';
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';
export const CHECK_AUTH_FAILURE = 'CHECK_AUTH_FAILURE';
