export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';

export const TOGGLE_OBJECT_BUSY = 'TOGGLE_OBJECT_BUSY';

export const TOGGLE_REPORT_BUSY = 'TOGGLE_REPORT_BUSY';
export const TOGGLE_REPORT_EDIT_MODE = 'TOGGLE_REPORT_EDIT_MODE';

export const TOGGLE_PLAN_BUSY = 'TOGGLE_PLAN_BUSY';

export const TOGGLE_PROFILE_BUSY = 'TOGGLE_PROFILE_BUSY';
export const TOGGLE_PROFILE_EDIT_MODE = 'TOGGLE_PROFILE_EDIT_MODE';

export const TOGGLE_REPORTS_BUSY = 'TOGGLE_REPORTS_BUSY';

export const TOGGLE_STATISTICS_BUSY = 'TOGGLE_STATISTICS_BUSY';

export const TOGGLE_LOCAL_REPORT_SAVING = 'TOGGLE_LOCAL_REPORT_SAVING';
