export const CHANGE_EXPORT_SELECTED_TEMPLATE = 'CHANGE_EXPORT_SELECTED_TEMPLATE';
export const TOGGLE_EXPORT_EMAIL_ENABLED = 'TOGGLE_EXPORT_EMAIL_ENABLED';
export const CHANGE_EXPORT_EMAIL_ADDRESS = 'CHANGE_EXPORT_EMAIL_ADDRESS';
