export const CHANGE_OBJECTS_FILTER = 'CHANGE_OBJECTS_FILTER';
export const TOGGLE_OBJECTS_COMPANIES_FILTER_EXPANDED = 'TOGGLE_OBJECTS_COMPANIES_FILTER_EXPANDED';
export const TOGGLE_OBJECTS_GROUP_VISIBLE = 'TOGGLE_OBJECTS_GROUP_VISIBLE';
